### ISSUE TITLE
app-editors/appflowy-bin missing libmpv

### ISSUE THREAD

**Issue by mbaraa** [Gentoo-zh/gentoo-zh#4810]
When installing `app-editors/appflowy-bin` from this overlay, it doesn't run properly, exiting with this error 

```
/opt/appflowy-bin/AppFlowy: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

Any idea or possible fixes?

**Comment by Linerre** [comment]
I think the problem may be that `appflowy-bin` requires `libmpv.so.1` as one of its runtime deps. But `media-video/mpv` (v0.38.0) now ships `libmpv.so.2` only.

I'm thinking about the follow solution:
1. add  `media-video/mpv` as runtime dep to  `appflowy-bin` 
2. add sth like `dosym libmpv.so.1 libmpv.so.2` to the ebuild in the install phase or post-install phase

At the moment, could you try to emerge `media-video/mpv` and manually symlink `libmpv.so.1` to `libmpv.so.2` (or to `libmpv.so`).  They are all put under `/usr/lib64/`.  Just to make sure `libmpv.so.2` actually works.  

Otherwise if only `libmpv.so.1` works, then the only possible fix I can think of is downgrading runtime dep to the version of mpv that provides `libmpv.so.1`.

**Comment by mbaraa** [comment]
Thanks m8, that worked!
